### PR TITLE
Map error for bytes32 key conversion as std error

### PR DESCRIPTION
**Pull request by hskang9**
`unwrap` shouldn't be allowed in a rust code. I add a error mapping logic where hex decode error in storage key can be displayed as StdError.

### CODE REVIEW

**Review by joshuajbouw — CHANGES_REQUESTED** [review]
It would need to be much more than just this. The scope indicates that all `unwrap` will be removed, but only one was? Error handling in general is completely absent.

**Comment by aleksuss** [comment]
Let's postpone this one. Will do this a bit later.

**Comment by hskang9** [comment]
I replaced `unwrap()` with `expect` for comparing input.

**Comment by hskang9** [comment]
@aleksuss @joshuajbouw

**Pull request closed without merging**
